<?php

return [
    // Main title
    'title' => 'Portal',
    
    // Navigation menu
    'navigation' => [
        'dashboard' => 'Dashboard',
        'preparation' => 'Preparation',
        'documents' => 'Documents',
        'participants' => 'Participants',
        'event_activity' => 'Event & Activity',
        'announcements' => 'Announcements',
        'score_games' => 'Score Games',
        'surveys' => 'Surveys',
        'environment' => 'Environment',
        'halls' => 'Halls',
        'virtual_stands' => 'Virtual Stands',
        'system_management' => 'System Management',
        'tenants' => 'Tenants',
        'countries' => 'Countries',
        'languages' => 'Languages',
        'currencies' => 'Currencies',
        'timezones' => 'Timezones',
        'reports' => 'Reports',
        'users' => 'Users',
        'settings' => 'Settings',
    ],
    
    // Header
    'header' => [
        'search' => 'Search',
        'search_placeholder' => 'Search...',
        'toggle_theme' => 'Toggle theme',
        'notifications' => 'Notifications',
        'user_menu' => 'User menu',
        'default_user' => 'User',
    ],
    
    // Profile menu
    'profile_menu' => [
        'profile' => 'My Profile',
        'logout' => 'Logout',
    ],
    
    // Footer
    'footer' => [
        'copyright' => '© :year :company. All rights reserved.',
        'version' => 'Version :version',
        'made_with' => 'Made with',
        'by' => 'by',
    ],
    
    // General
    'general' => [
        'loading' => 'Loading...',
        'error' => 'An error occurred',
        'success' => 'Operation successful',
        'warning' => 'Warning',
        'info' => 'Info',
        'general' => 'General',
        'contact' => 'Contact',
        'localization' => 'Localization',
        'subscription' => 'Subscription',
    ],
    
    // Settings
    'settings' => [
        'title' => 'Settings',
        'subtitle' => 'Manage your organization information and preferences',
        'description' => 'Manage your account settings and preferences',
        'tabs' => [
            'general' => 'General',
            'contact' => 'Contact',
            'localization' => 'Localization',
            'subscription' => 'Subscription',
            'security' => 'Security',
            'notifications' => 'Notifications',
        ],
        'fields' => [
            'name' => 'Organization Name',
            'legal_name' => 'Legal Name',
            'code' => 'Organization Code',
            'slug' => 'URL Slug',
            'type' => 'Organization Type',
            'email' => 'Email',
            'phone' => 'Phone',
            'website' => 'Website',
            'address_line_1' => 'Address Line 1',
            'address_line_2' => 'Address Line 2',
            'city' => 'City',
            'state' => 'State/Province',
            'postal_code' => 'Postal Code',
            'country' => 'Country',
            'language' => 'Language',
            'currency' => 'Currency',
            'timezone' => 'Timezone',
            'date_format' => 'Date Format',
            'time_format' => 'Time Format',
        ],
        'hints' => [
            'name' => 'This name will be visible to all users',
            'code' => 'Automatically generated by the system',
        ],
        'placeholders' => [
            'select_country' => 'Select Country',
            'select_language' => 'Select Language',
            'select_currency' => 'Select Currency',
            'select_timezone' => 'Select Timezone',
        ],
        'buttons' => [
            'save' => 'Save Changes',
            'saving' => 'Saving...',
            'cancel' => 'Cancel',
        ],
        'messages' => [
            'updated_successfully' => 'Settings updated successfully',
            'update_failed' => 'Failed to update settings',
        ],
        'subscription' => [
            'current_plan' => 'Current Plan',
            'plan' => 'Plan',
            'status' => 'Status',
            'expires' => 'Expires',
            'users' => 'Users',
            'storage' => 'Storage',
            'events' => 'Events',
            'used' => 'used',
        ],
        'save_changes' => 'Save Changes',
        'saving' => 'Saving...',
        'success' => 'Success',
        'save_failed' => 'Save failed',
        'passwords_not_match' => 'Passwords do not match',
        'general' => [
            'profile' => [
                'title' => 'Profile Information',
                'description' => 'Update your basic profile information',
                'first_name' => 'First Name',
                'first_name_placeholder' => 'Enter your first name',
                'last_name' => 'Last Name',
                'last_name_placeholder' => 'Enter your last name',
                'email' => 'Email Address',
                'email_placeholder' => 'Enter your email address',
            ],
            'preferences' => [
                'title' => 'Preferences',
                'description' => 'Customize your language and date settings',
                'language' => 'Language',
                'timezone' => 'Timezone',
                'date_format' => 'Date Format',
            ],
        ],
        'security' => [
            'password' => [
                'title' => 'Change Password',
                'description' => 'Use a strong password to secure your account',
                'current' => 'Current Password',
                'new' => 'New Password',
                'confirm' => 'Confirm New Password',
                'requirements' => 'At least 8 characters with one uppercase, one lowercase, one number and one special character',
            ],
            'two_factor' => [
                'title' => 'Two-Factor Authentication',
                'description' => 'Add an extra layer of security to your account',
                'status' => 'Status',
                'enabled' => 'Enabled',
                'disabled' => 'Disabled',
                'enable' => 'Enable',
                'disable' => 'Disable',
            ],
        ],
        'notifications' => [
            'email' => [
                'title' => 'Email Notifications',
                'description' => 'Choose which emails you want to receive',
                'updates' => 'Product updates and news',
                'security' => 'Security alerts and important notifications',
                'marketing' => 'Marketing and promotional emails',
            ],
        ],
    ],
]; 