<?php

return [
    'title' => 'Settings',
    'subtitle' => 'Manage your organization information and preferences',
    'select_tab' => 'Select settings category',
    
    // Tabs
    'tabs' => [
        'general' => 'General',
        'contact' => 'Contact',
        'localization' => 'Localization',
        'subscription' => 'Subscription',
    ],
    
    // Sections
    'sections' => [
        'organization_info' => 'Organization Information',
        'contact_info' => 'Contact Information',
        'address' => 'Address',
        'regional_settings' => 'Regional Settings',
        'datetime_formats' => 'Date & Time Formats',
    ],
    
    // Fields
    'fields' => [
        // Organization
        'organization_name' => 'Organization Name',
        'legal_name' => 'Legal Name',
        'organization_code' => 'Organization Code',
        'url_slug' => 'URL Slug',
        
        // Contact
        'email' => 'Email Address',
        'phone' => 'Phone Number',
        'website' => 'Website',
        
        // Address
        'address_line_1' => 'Address Line 1',
        'address_line_2' => 'Address Line 2',
        'city' => 'City',
        'state' => 'State/Province',
        'postal_code' => 'Postal Code',
        'country' => 'Country',
        
        // Localization
        'language' => 'Language',
        'currency' => 'Currency',
        'timezone' => 'Timezone',
        'date_format' => 'Date Format',
        'time_format' => 'Time Format',
    ],
    
    // Placeholders
    'placeholders' => [
        'organization_name' => 'Acme Corporation',
        'legal_name' => 'Acme Corporation Ltd.',
        'email' => 'contact@example.com',
        'phone' => '+1 (555) 123-4567',
        'address_line_1' => '123 Main Street',
        'address_line_2' => 'Suite 100',
        'city' => 'New York',
        'state' => 'NY',
        'postal_code' => '10001',
        'select_country' => 'Select a country',
        'select_language' => 'Select a language',
        'select_currency' => 'Select a currency',
        'select_timezone' => 'Select a timezone',
    ],
    
    // Hints
    'hints' => [
        'organization_name' => 'This name will be visible to all users',
        'organization_code' => 'Automatically generated by the system',
        'phone' => 'Include country code for international numbers',
        'save_changes' => 'All changes will take effect immediately',
    ],
    
    // Subscription
    'subscription' => [
        'current_plan' => 'Current Subscription Plan',
        'plan' => 'Plan',
        'status' => 'Status',
        'expires' => 'Expires',
        'usage_statistics' => 'Usage Statistics',
        'users' => 'Users',
        'storage' => 'Storage',
        'events' => 'Events',
        'used' => 'used',
    ],
    
    // Messages
    'messages' => [
        'saved_successfully' => 'Settings have been saved successfully',
        'save_failed' => 'Failed to save settings. Please try again.',
    ],
]; 