<?php

return [
    'title' => 'Settings',
    'subtitle' => 'Manage your organization information and preferences',
    'select_tab' => 'Select settings category',
    
    // Tabs
    'tabs' => [
        'general' => 'General',
        'contact' => 'Contact',
        'localization' => 'Localization',
        'subscription' => 'Subscription',
    ],
    
    // Sections
    'sections' => [
        'organization_info' => 'Organization Information',
        'contact_info' => 'Contact Information',
        'address' => 'Address',
        'regional_settings' => 'Regional Settings',
        'datetime_formats' => 'Date & Time Formats',
    ],
    
    // Fields
    'fields' => [
        // Organization
        'organization_name' => 'Organization Name',
        'legal_name' => 'Legal Name',
        'organization_code' => 'Organization Code',
        'organization_id' => 'Organization ID',
        'url_slug' => 'URL Slug',
        
        // Contact
        'email' => 'Email Address',
        'phone' => 'Phone Number',
        'website' => 'Website',
        
        // Address
        'address_line_1' => 'Address Line 1',
        'address_line_2' => 'Address Line 2',
        'city' => 'City',
        'state' => 'State/Province',
        'postal_code' => 'Postal Code',
        'country' => 'Country',
        
        // Localization
        'language' => 'Language',
        'currency' => 'Currency',
        'timezone' => 'Timezone',
        'date_format' => 'Date Format',
        'time_format' => 'Time Format',
    ],
    
    // Placeholders
    'placeholders' => [
        'organization_name' => 'Acme Corporation',
        'legal_name' => 'Acme Corporation Ltd.',
        'email' => 'contact@example.com',
        'phone' => '+1 (555) 123-4567',
        'address_line_1' => '123 Main Street',
        'address_line_2' => 'Suite 100',
        'city' => 'New York',
        'state' => 'NY',
        'postal_code' => '10001',
        'select_country' => 'Select a country',
        'select_language' => 'Select a language',
        'select_currency' => 'Select a currency',
        'select_timezone' => 'Select a timezone',
    ],
    
    // Hints
    'hints' => [
        'organization_name' => 'This name will be visible to all users',
        'legal_name' => 'Official registered name for legal documents and invoices',
        'organization_code' => 'Automatically generated by the system',
        'organization_id' => 'Unique identifier for your organization in the system',
        'phone' => 'Primary contact number for business communications',
        'email' => 'Primary contact email for your organization',
        'website' => 'Your organization\'s website URL',
        'address_line_1' => 'Street address, P.O. box, company name',
        'address_line_2' => 'Apartment, suite, unit, building, floor, etc.',
        'city' => 'City or locality name',
        'state' => 'State, province, or region',
        'postal_code' => 'ZIP or postal code',
        'country' => 'Country for address and regional settings',
        'language' => 'Default language for the organization',
        'currency' => 'Default currency for financial transactions',
        'timezone' => 'Time zone for scheduling and timestamps',
        'date_format' => 'How dates are displayed throughout the system',
        'time_format' => 'How times are displayed throughout the system',
        'save_changes' => 'Changes will be applied immediately after saving',
        'no_changes' => 'No changes to save',
    ],
    
    // Date formats
    'date_formats' => [
        'full' => 'Full date',
        'full_us' => 'Full date (US)',
        'medium' => 'Medium date',
        'medium_us' => 'Medium date (US)',
    ],
    
    // Subscription
    'subscription' => [
        'current_plan' => 'Current Subscription Plan',
        'plan' => 'Plan',
        'status' => 'Status',
        'expires' => 'Expires',
        'usage_statistics' => 'Usage Statistics',
        'users' => 'Users',
        'storage' => 'Storage',
        'events' => 'Events',
        'used' => 'used',
    ],
    
    // Messages
    'messages' => [
        'saved_successfully' => 'Settings have been saved successfully',
        'save_failed' => 'Failed to save settings. Please try again.',
    ],
]; 