<?php

namespace Database\Seeders\System;

use App\Models\System\Language;
use Illuminate\Database\Seeder;

class LanguagesSeeder extends Seeder
{
    public function run(): void
    {
        $languages = [
            // English (Active)
            [
                'iso_639_1' => 'en',
                'iso_639_2' => 'eng',
                'iso_639_3' => 'eng',
                'name_en' => 'English',
                'name_native' => 'English',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['US', 'GB', 'CA', 'AU', 'NZ', 'IE'],
                'speakers_native' => 379000000,
                'speakers_total' => 1452000000,
                'is_active' => true,
                'is_translated' => true,
            ],
            // Turkish (Active)
            [
                'iso_639_1' => 'tr',
                'iso_639_2' => 'tur',
                'iso_639_3' => 'tur',
                'name_en' => 'Turkish',
                'name_native' => 'Türkçe',
                'family' => 'Turkic',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['TR', 'CY'],
                'speakers_native' => 88000000,
                'speakers_total' => 90000000,
                'is_active' => true,
                'is_translated' => true,
            ],
            // Arabic (Inactive)
            [
                'iso_639_1' => 'ar',
                'iso_639_2' => 'ara',
                'iso_639_3' => 'ara',
                'name_en' => 'Arabic',
                'name_native' => 'العربية',
                'family' => 'Afro-Asiatic',
                'script' => 'Arabic',
                'direction' => 'rtl',
                'countries' => ['SA', 'EG', 'IQ', 'AE', 'JO', 'LB', 'SY', 'MA', 'TN', 'DZ'],
                'speakers_native' => 422000000,
                'speakers_total' => 520000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Spanish (Inactive)
            [
                'iso_639_1' => 'es',
                'iso_639_2' => 'spa',
                'iso_639_3' => 'spa',
                'name_en' => 'Spanish',
                'name_native' => 'Español',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['ES', 'MX', 'AR', 'CO', 'VE', 'CL', 'PE', 'EC', 'GT', 'CU'],
                'speakers_native' => 493000000,
                'speakers_total' => 559000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // French (Inactive)
            [
                'iso_639_1' => 'fr',
                'iso_639_2' => 'fra',
                'iso_639_3' => 'fra',
                'name_en' => 'French',
                'name_native' => 'Français',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['FR', 'CA', 'BE', 'CH', 'LU', 'MC', 'SN', 'CI', 'ML', 'BF'],
                'speakers_native' => 280000000,
                'speakers_total' => 321000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // German (Inactive)
            [
                'iso_639_1' => 'de',
                'iso_639_2' => 'deu',
                'iso_639_3' => 'deu',
                'name_en' => 'German',
                'name_native' => 'Deutsch',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['DE', 'AT', 'CH', 'LI', 'LU', 'BE'],
                'speakers_native' => 95000000,
                'speakers_total' => 132000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Chinese (Mandarin) (Inactive)
            [
                'iso_639_1' => 'zh',
                'iso_639_2' => 'zho',
                'iso_639_3' => 'zho',
                'name_en' => 'Chinese',
                'name_native' => '中文',
                'family' => 'Sino-Tibetan',
                'script' => 'Chinese',
                'direction' => 'ltr',
                'countries' => ['CN', 'TW', 'SG', 'MY'],
                'speakers_native' => 918000000,
                'speakers_total' => 1120000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Russian (Inactive)
            [
                'iso_639_1' => 'ru',
                'iso_639_2' => 'rus',
                'iso_639_3' => 'rus',
                'name_en' => 'Russian',
                'name_native' => 'Русский',
                'family' => 'Indo-European',
                'script' => 'Cyrillic',
                'direction' => 'ltr',
                'countries' => ['RU', 'BY', 'KZ', 'KG'],
                'speakers_native' => 154000000,
                'speakers_total' => 258000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Portuguese (Inactive)
            [
                'iso_639_1' => 'pt',
                'iso_639_2' => 'por',
                'iso_639_3' => 'por',
                'name_en' => 'Portuguese',
                'name_native' => 'Português',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['BR', 'PT', 'AO', 'MZ', 'GW', 'TL', 'CV', 'ST'],
                'speakers_native' => 264000000,
                'speakers_total' => 280000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Japanese (Inactive)
            [
                'iso_639_1' => 'ja',
                'iso_639_2' => 'jpn',
                'iso_639_3' => 'jpn',
                'name_en' => 'Japanese',
                'name_native' => '日本語',
                'family' => 'Japonic',
                'script' => 'Japanese',
                'direction' => 'ltr',
                'countries' => ['JP'],
                'speakers_native' => 128000000,
                'speakers_total' => 128300000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Hindi (Inactive)
            [
                'iso_639_1' => 'hi',
                'iso_639_2' => 'hin',
                'iso_639_3' => 'hin',
                'name_en' => 'Hindi',
                'name_native' => 'हिन्दी',
                'family' => 'Indo-European',
                'script' => 'Devanagari',
                'direction' => 'ltr',
                'countries' => ['IN', 'NP', 'FJ'],
                'speakers_native' => 602000000,
                'speakers_total' => 637000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Italian (Inactive)
            [
                'iso_639_1' => 'it',
                'iso_639_2' => 'ita',
                'iso_639_3' => 'ita',
                'name_en' => 'Italian',
                'name_native' => 'Italiano',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['IT', 'CH', 'SM', 'VA'],
                'speakers_native' => 64000000,
                'speakers_total' => 85000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Korean (Inactive)
            [
                'iso_639_1' => 'ko',
                'iso_639_2' => 'kor',
                'iso_639_3' => 'kor',
                'name_en' => 'Korean',
                'name_native' => '한국어',
                'family' => 'Koreanic',
                'script' => 'Hangul',
                'direction' => 'ltr',
                'countries' => ['KR', 'KP'],
                'speakers_native' => 80000000,
                'speakers_total' => 82000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Dutch (Inactive)
            [
                'iso_639_1' => 'nl',
                'iso_639_2' => 'nld',
                'iso_639_3' => 'nld',
                'name_en' => 'Dutch',
                'name_native' => 'Nederlands',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['NL', 'BE', 'SR'],
                'speakers_native' => 25000000,
                'speakers_total' => 30000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Polish (Inactive)
            [
                'iso_639_1' => 'pl',
                'iso_639_2' => 'pol',
                'iso_639_3' => 'pol',
                'name_en' => 'Polish',
                'name_native' => 'Polski',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['PL'],
                'speakers_native' => 40000000,
                'speakers_total' => 45000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Swedish (Inactive)
            [
                'iso_639_1' => 'sv',
                'iso_639_2' => 'swe',
                'iso_639_3' => 'swe',
                'name_en' => 'Swedish',
                'name_native' => 'Svenska',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['SE', 'FI'],
                'speakers_native' => 10000000,
                'speakers_total' => 13000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Norwegian (Inactive)
            [
                'iso_639_1' => 'no',
                'iso_639_2' => 'nor',
                'iso_639_3' => 'nor',
                'name_en' => 'Norwegian',
                'name_native' => 'Norsk',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['NO'],
                'speakers_native' => 5000000,
                'speakers_total' => 5200000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Danish (Inactive)
            [
                'iso_639_1' => 'da',
                'iso_639_2' => 'dan',
                'iso_639_3' => 'dan',
                'name_en' => 'Danish',
                'name_native' => 'Dansk',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['DK', 'GL', 'FO'],
                'speakers_native' => 6000000,
                'speakers_total' => 6500000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Finnish (Inactive)
            [
                'iso_639_1' => 'fi',
                'iso_639_2' => 'fin',
                'iso_639_3' => 'fin',
                'name_en' => 'Finnish',
                'name_native' => 'Suomi',
                'family' => 'Uralic',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['FI'],
                'speakers_native' => 5500000,
                'speakers_total' => 5800000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Greek (Inactive)
            [
                'iso_639_1' => 'el',
                'iso_639_2' => 'ell',
                'iso_639_3' => 'ell',
                'name_en' => 'Greek',
                'name_native' => 'Ελληνικά',
                'family' => 'Indo-European',
                'script' => 'Greek',
                'direction' => 'ltr',
                'countries' => ['GR', 'CY'],
                'speakers_native' => 13500000,
                'speakers_total' => 14000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Czech (Inactive)
            [
                'iso_639_1' => 'cs',
                'iso_639_2' => 'ces',
                'iso_639_3' => 'ces',
                'name_en' => 'Czech',
                'name_native' => 'Čeština',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['CZ'],
                'speakers_native' => 10700000,
                'speakers_total' => 12000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Hungarian (Inactive)
            [
                'iso_639_1' => 'hu',
                'iso_639_2' => 'hun',
                'iso_639_3' => 'hun',
                'name_en' => 'Hungarian',
                'name_native' => 'Magyar',
                'family' => 'Uralic',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['HU'],
                'speakers_native' => 13000000,
                'speakers_total' => 14500000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Romanian (Inactive)
            [
                'iso_639_1' => 'ro',
                'iso_639_2' => 'ron',
                'iso_639_3' => 'ron',
                'name_en' => 'Romanian',
                'name_native' => 'Română',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['RO', 'MD'],
                'speakers_native' => 24000000,
                'speakers_total' => 25000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Bulgarian (Inactive)
            [
                'iso_639_1' => 'bg',
                'iso_639_2' => 'bul',
                'iso_639_3' => 'bul',
                'name_en' => 'Bulgarian',
                'name_native' => 'Български',
                'family' => 'Indo-European',
                'script' => 'Cyrillic',
                'direction' => 'ltr',
                'countries' => ['BG'],
                'speakers_native' => 8000000,
                'speakers_total' => 9000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Slovak (Inactive)
            [
                'iso_639_1' => 'sk',
                'iso_639_2' => 'slk',
                'iso_639_3' => 'slk',
                'name_en' => 'Slovak',
                'name_native' => 'Slovenčina',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['SK'],
                'speakers_native' => 5200000,
                'speakers_total' => 5600000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Croatian (Inactive)
            [
                'iso_639_1' => 'hr',
                'iso_639_2' => 'hrv',
                'iso_639_3' => 'hrv',
                'name_en' => 'Croatian',
                'name_native' => 'Hrvatski',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['HR', 'BA'],
                'speakers_native' => 5500000,
                'speakers_total' => 6000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Serbian (Inactive)
            [
                'iso_639_1' => 'sr',
                'iso_639_2' => 'srp',
                'iso_639_3' => 'srp',
                'name_en' => 'Serbian',
                'name_native' => 'Српски',
                'family' => 'Indo-European',
                'script' => 'Cyrillic',
                'direction' => 'ltr',
                'countries' => ['RS', 'BA', 'ME', 'XK'],
                'speakers_native' => 9000000,
                'speakers_total' => 10000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Albanian (Inactive)
            [
                'iso_639_1' => 'sq',
                'iso_639_2' => 'sqi',
                'iso_639_3' => 'sqi',
                'name_en' => 'Albanian',
                'name_native' => 'Shqip',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['AL', 'XK', 'MK'],
                'speakers_native' => 7500000,
                'speakers_total' => 7600000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Kurdish (Inactive)
            [
                'iso_639_1' => 'ku',
                'iso_639_2' => 'kur',
                'iso_639_3' => 'kur',
                'name_en' => 'Kurdish',
                'name_native' => 'Kurdî',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['TR', 'IQ', 'IR', 'SY'],
                'speakers_native' => 30000000,
                'speakers_total' => 35000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Ukrainian (Inactive)
            [
                'iso_639_1' => 'uk',
                'iso_639_2' => 'ukr',
                'iso_639_3' => 'ukr',
                'name_en' => 'Ukrainian',
                'name_native' => 'Українська',
                'family' => 'Indo-European',
                'script' => 'Cyrillic',
                'direction' => 'ltr',
                'countries' => ['UA'],
                'speakers_native' => 33000000,
                'speakers_total' => 40000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Hebrew (Inactive)
            [
                'iso_639_1' => 'he',
                'iso_639_2' => 'heb',
                'iso_639_3' => 'heb',
                'name_en' => 'Hebrew',
                'name_native' => 'עברית',
                'family' => 'Afro-Asiatic',
                'script' => 'Hebrew',
                'direction' => 'rtl',
                'countries' => ['IL'],
                'speakers_native' => 9000000,
                'speakers_total' => 9500000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Persian/Farsi (Inactive)
            [
                'iso_639_1' => 'fa',
                'iso_639_2' => 'fas',
                'iso_639_3' => 'fas',
                'name_en' => 'Persian',
                'name_native' => 'فارسی',
                'family' => 'Indo-European',
                'script' => 'Arabic',
                'direction' => 'rtl',
                'countries' => ['IR', 'AF', 'TJ'],
                'speakers_native' => 70000000,
                'speakers_total' => 110000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Azerbaijani (Inactive)
            [
                'iso_639_1' => 'az',
                'iso_639_2' => 'aze',
                'iso_639_3' => 'aze',
                'name_en' => 'Azerbaijani',
                'name_native' => 'Azərbaycan',
                'family' => 'Turkic',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['AZ', 'IR'],
                'speakers_native' => 23000000,
                'speakers_total' => 30000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Kazakh (Inactive)
            [
                'iso_639_1' => 'kk',
                'iso_639_2' => 'kaz',
                'iso_639_3' => 'kaz',
                'name_en' => 'Kazakh',
                'name_native' => 'Қазақ',
                'family' => 'Turkic',
                'script' => 'Cyrillic',
                'direction' => 'ltr',
                'countries' => ['KZ'],
                'speakers_native' => 13000000,
                'speakers_total' => 15000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Uzbek (Inactive)
            [
                'iso_639_1' => 'uz',
                'iso_639_2' => 'uzb',
                'iso_639_3' => 'uzb',
                'name_en' => 'Uzbek',
                'name_native' => 'Oʻzbek',
                'family' => 'Turkic',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['UZ', 'AF'],
                'speakers_native' => 35000000,
                'speakers_total' => 40000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Thai (Inactive)
            [
                'iso_639_1' => 'th',
                'iso_639_2' => 'tha',
                'iso_639_3' => 'tha',
                'name_en' => 'Thai',
                'name_native' => 'ไทย',
                'family' => 'Kra-Dai',
                'script' => 'Thai',
                'direction' => 'ltr',
                'countries' => ['TH'],
                'speakers_native' => 61000000,
                'speakers_total' => 69000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Vietnamese (Inactive)
            [
                'iso_639_1' => 'vi',
                'iso_639_2' => 'vie',
                'iso_639_3' => 'vie',
                'name_en' => 'Vietnamese',
                'name_native' => 'Tiếng Việt',
                'family' => 'Austroasiatic',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['VN'],
                'speakers_native' => 85000000,
                'speakers_total' => 95000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Indonesian (Inactive)
            [
                'iso_639_1' => 'id',
                'iso_639_2' => 'ind',
                'iso_639_3' => 'ind',
                'name_en' => 'Indonesian',
                'name_native' => 'Bahasa Indonesia',
                'family' => 'Austronesian',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['ID'],
                'speakers_native' => 43000000,
                'speakers_total' => 199000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Malay (Inactive)
            [
                'iso_639_1' => 'ms',
                'iso_639_2' => 'msa',
                'iso_639_3' => 'msa',
                'name_en' => 'Malay',
                'name_native' => 'Bahasa Melayu',
                'family' => 'Austronesian',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['MY', 'SG', 'BN'],
                'speakers_native' => 33000000,
                'speakers_total' => 290000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Bengali (Inactive)
            [
                'iso_639_1' => 'bn',
                'iso_639_2' => 'ben',
                'iso_639_3' => 'ben',
                'name_en' => 'Bengali',
                'name_native' => 'বাংলা',
                'family' => 'Indo-European',
                'script' => 'Bengali',
                'direction' => 'ltr',
                'countries' => ['BD', 'IN'],
                'speakers_native' => 300000000,
                'speakers_total' => 320000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Urdu (Inactive)
            [
                'iso_639_1' => 'ur',
                'iso_639_2' => 'urd',
                'iso_639_3' => 'urd',
                'name_en' => 'Urdu',
                'name_native' => 'اردو',
                'family' => 'Indo-European',
                'script' => 'Arabic',
                'direction' => 'rtl',
                'countries' => ['PK', 'IN'],
                'speakers_native' => 70000000,
                'speakers_total' => 231000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Tagalog/Filipino (Inactive)
            [
                'iso_639_1' => 'tl',
                'iso_639_2' => 'tgl',
                'iso_639_3' => 'tgl',
                'name_en' => 'Tagalog',
                'name_native' => 'Tagalog',
                'family' => 'Austronesian',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['PH'],
                'speakers_native' => 29000000,
                'speakers_total' => 82000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Lithuanian (Inactive)
            [
                'iso_639_1' => 'lt',
                'iso_639_2' => 'lit',
                'iso_639_3' => 'lit',
                'name_en' => 'Lithuanian',
                'name_native' => 'Lietuvių',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['LT'],
                'speakers_native' => 3000000,
                'speakers_total' => 3200000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Latvian (Inactive)
            [
                'iso_639_1' => 'lv',
                'iso_639_2' => 'lav',
                'iso_639_3' => 'lav',
                'name_en' => 'Latvian',
                'name_native' => 'Latviešu',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['LV'],
                'speakers_native' => 1750000,
                'speakers_total' => 2000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Estonian (Inactive)
            [
                'iso_639_1' => 'et',
                'iso_639_2' => 'est',
                'iso_639_3' => 'est',
                'name_en' => 'Estonian',
                'name_native' => 'Eesti',
                'family' => 'Uralic',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['EE'],
                'speakers_native' => 1100000,
                'speakers_total' => 1200000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Slovenian (Inactive)
            [
                'iso_639_1' => 'sl',
                'iso_639_2' => 'slv',
                'iso_639_3' => 'slv',
                'name_en' => 'Slovenian',
                'name_native' => 'Slovenščina',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['SI'],
                'speakers_native' => 2500000,
                'speakers_total' => 2600000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Macedonian (Inactive)
            [
                'iso_639_1' => 'mk',
                'iso_639_2' => 'mkd',
                'iso_639_3' => 'mkd',
                'name_en' => 'Macedonian',
                'name_native' => 'Македонски',
                'family' => 'Indo-European',
                'script' => 'Cyrillic',
                'direction' => 'ltr',
                'countries' => ['MK'],
                'speakers_native' => 2000000,
                'speakers_total' => 2100000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Georgian (Inactive)
            [
                'iso_639_1' => 'ka',
                'iso_639_2' => 'kat',
                'iso_639_3' => 'kat',
                'name_en' => 'Georgian',
                'name_native' => 'ქართული',
                'family' => 'Kartvelian',
                'script' => 'Georgian',
                'direction' => 'ltr',
                'countries' => ['GE'],
                'speakers_native' => 3700000,
                'speakers_total' => 4000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Armenian (Inactive)
            [
                'iso_639_1' => 'hy',
                'iso_639_2' => 'hye',
                'iso_639_3' => 'hye',
                'name_en' => 'Armenian',
                'name_native' => 'Հայերեն',
                'family' => 'Indo-European',
                'script' => 'Armenian',
                'direction' => 'ltr',
                'countries' => ['AM'],
                'speakers_native' => 5000000,
                'speakers_total' => 7000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Icelandic (Inactive)
            [
                'iso_639_1' => 'is',
                'iso_639_2' => 'isl',
                'iso_639_3' => 'isl',
                'name_en' => 'Icelandic',
                'name_native' => 'Íslenska',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['IS'],
                'speakers_native' => 350000,
                'speakers_total' => 360000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Irish (Inactive)
            [
                'iso_639_1' => 'ga',
                'iso_639_2' => 'gle',
                'iso_639_3' => 'gle',
                'name_en' => 'Irish',
                'name_native' => 'Gaeilge',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['IE'],
                'speakers_native' => 140000,
                'speakers_total' => 1900000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Welsh (Inactive)
            [
                'iso_639_1' => 'cy',
                'iso_639_2' => 'cym',
                'iso_639_3' => 'cym',
                'name_en' => 'Welsh',
                'name_native' => 'Cymraeg',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['GB'],
                'speakers_native' => 875000,
                'speakers_total' => 1500000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Basque (Inactive)
            [
                'iso_639_1' => 'eu',
                'iso_639_2' => 'eus',
                'iso_639_3' => 'eus',
                'name_en' => 'Basque',
                'name_native' => 'Euskara',
                'family' => 'Language isolate',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['ES', 'FR'],
                'speakers_native' => 750000,
                'speakers_total' => 1200000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Catalan (Inactive)
            [
                'iso_639_1' => 'ca',
                'iso_639_2' => 'cat',
                'iso_639_3' => 'cat',
                'name_en' => 'Catalan',
                'name_native' => 'Català',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['ES', 'AD', 'FR', 'IT'],
                'speakers_native' => 4100000,
                'speakers_total' => 10000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Galician
            [
                'iso_639_1' => 'gl',
                'iso_639_2' => 'glg',
                'iso_639_3' => 'glg',
                'name_en' => 'Galician',
                'name_native' => 'Galego',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['ES'],
                'speakers_native' => 2400000,
                'speakers_total' => 2800000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Luxembourgish
            [
                'iso_639_1' => 'lb',
                'iso_639_2' => 'ltz',
                'iso_639_3' => 'ltz',
                'name_en' => 'Luxembourgish',
                'name_native' => 'Lëtzebuergesch',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['LU'],
                'speakers_native' => 400000,
                'speakers_total' => 600000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Maltese
            [
                'iso_639_1' => 'mt',
                'iso_639_2' => 'mlt',
                'iso_639_3' => 'mlt',
                'name_en' => 'Maltese',
                'name_native' => 'Malti',
                'family' => 'Afro-Asiatic',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['MT'],
                'speakers_native' => 520000,
                'speakers_total' => 530000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Belarusian
            [
                'iso_639_1' => 'be',
                'iso_639_2' => 'bel',
                'iso_639_3' => 'bel',
                'name_en' => 'Belarusian',
                'name_native' => 'Беларуская',
                'family' => 'Indo-European',
                'script' => 'Cyrillic',
                'direction' => 'ltr',
                'countries' => ['BY'],
                'speakers_native' => 7000000,
                'speakers_total' => 8000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Bosnian
            [
                'iso_639_1' => 'bs',
                'iso_639_2' => 'bos',
                'iso_639_3' => 'bos',
                'name_en' => 'Bosnian',
                'name_native' => 'Bosanski',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['BA'],
                'speakers_native' => 2200000,
                'speakers_total' => 2500000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Afrikaans
            [
                'iso_639_1' => 'af',
                'iso_639_2' => 'afr',
                'iso_639_3' => 'afr',
                'name_en' => 'Afrikaans',
                'name_native' => 'Afrikaans',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['ZA', 'NA'],
                'speakers_native' => 7200000,
                'speakers_total' => 16000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Zulu
            [
                'iso_639_1' => 'zu',
                'iso_639_2' => 'zul',
                'iso_639_3' => 'zul',
                'name_en' => 'Zulu',
                'name_native' => 'isiZulu',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['ZA'],
                'speakers_native' => 12000000,
                'speakers_total' => 16000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Xhosa
            [
                'iso_639_1' => 'xh',
                'iso_639_2' => 'xho',
                'iso_639_3' => 'xho',
                'name_en' => 'Xhosa',
                'name_native' => 'isiXhosa',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['ZA'],
                'speakers_native' => 8200000,
                'speakers_total' => 11000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Swahili
            [
                'iso_639_1' => 'sw',
                'iso_639_2' => 'swa',
                'iso_639_3' => 'swa',
                'name_en' => 'Swahili',
                'name_native' => 'Kiswahili',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['KE', 'TZ', 'UG', 'CD', 'RW', 'BI'],
                'speakers_native' => 16000000,
                'speakers_total' => 100000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Amharic
            [
                'iso_639_1' => 'am',
                'iso_639_2' => 'amh',
                'iso_639_3' => 'amh',
                'name_en' => 'Amharic',
                'name_native' => 'አማርኛ',
                'family' => 'Afro-Asiatic',
                'script' => 'Ethiopic',
                'direction' => 'ltr',
                'countries' => ['ET'],
                'speakers_native' => 32000000,
                'speakers_total' => 57000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Tigrinya
            [
                'iso_639_1' => 'ti',
                'iso_639_2' => 'tir',
                'iso_639_3' => 'tir',
                'name_en' => 'Tigrinya',
                'name_native' => 'ትግርኛ',
                'family' => 'Afro-Asiatic',
                'script' => 'Ethiopic',
                'direction' => 'ltr',
                'countries' => ['ET', 'ER'],
                'speakers_native' => 7000000,
                'speakers_total' => 9000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Hausa
            [
                'iso_639_1' => 'ha',
                'iso_639_2' => 'hau',
                'iso_639_3' => 'hau',
                'name_en' => 'Hausa',
                'name_native' => 'Hausa',
                'family' => 'Afro-Asiatic',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['NG', 'NE', 'GH', 'CM'],
                'speakers_native' => 75000000,
                'speakers_total' => 150000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Yoruba
            [
                'iso_639_1' => 'yo',
                'iso_639_2' => 'yor',
                'iso_639_3' => 'yor',
                'name_en' => 'Yoruba',
                'name_native' => 'Yorùbá',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['NG', 'BJ', 'TG'],
                'speakers_native' => 45000000,
                'speakers_total' => 50000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Igbo
            [
                'iso_639_1' => 'ig',
                'iso_639_2' => 'ibo',
                'iso_639_3' => 'ibo',
                'name_en' => 'Igbo',
                'name_native' => 'Igbo',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['NG'],
                'speakers_native' => 30000000,
                'speakers_total' => 35000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Somali
            [
                'iso_639_1' => 'so',
                'iso_639_2' => 'som',
                'iso_639_3' => 'som',
                'name_en' => 'Somali',
                'name_native' => 'Soomaali',
                'family' => 'Afro-Asiatic',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['SO', 'DJ', 'ET', 'KE'],
                'speakers_native' => 16000000,
                'speakers_total' => 22000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Kinyarwanda
            [
                'iso_639_1' => 'rw',
                'iso_639_2' => 'kin',
                'iso_639_3' => 'kin',
                'name_en' => 'Kinyarwanda',
                'name_native' => 'Ikinyarwanda',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['RW', 'CD', 'UG'],
                'speakers_native' => 12000000,
                'speakers_total' => 20000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Chewa
            [
                'iso_639_1' => 'ny',
                'iso_639_2' => 'nya',
                'iso_639_3' => 'nya',
                'name_en' => 'Chewa',
                'name_native' => 'Chichewa',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['MW', 'ZM', 'MZ'],
                'speakers_native' => 10000000,
                'speakers_total' => 12000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Shona
            [
                'iso_639_1' => 'sn',
                'iso_639_2' => 'sna',
                'iso_639_3' => 'sna',
                'name_en' => 'Shona',
                'name_native' => 'chiShona',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['ZW', 'MZ'],
                'speakers_native' => 11000000,
                'speakers_total' => 12000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Lingala
            [
                'iso_639_1' => 'ln',
                'iso_639_2' => 'lin',
                'iso_639_3' => 'lin',
                'name_en' => 'Lingala',
                'name_native' => 'Lingála',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['CD', 'CG', 'CF', 'AO'],
                'speakers_native' => 15000000,
                'speakers_total' => 25000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Pashto
            [
                'iso_639_1' => 'ps',
                'iso_639_2' => 'pus',
                'iso_639_3' => 'pus',
                'name_en' => 'Pashto',
                'name_native' => 'پښتو',
                'family' => 'Indo-European',
                'script' => 'Arabic',
                'direction' => 'rtl',
                'countries' => ['AF', 'PK'],
                'speakers_native' => 40000000,
                'speakers_total' => 60000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Sinhala
            [
                'iso_639_1' => 'si',
                'iso_639_2' => 'sin',
                'iso_639_3' => 'sin',
                'name_en' => 'Sinhala',
                'name_native' => 'සිංහල',
                'family' => 'Indo-European',
                'script' => 'Sinhala',
                'direction' => 'ltr',
                'countries' => ['LK'],
                'speakers_native' => 16000000,
                'speakers_total' => 17000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Tamil
            [
                'iso_639_1' => 'ta',
                'iso_639_2' => 'tam',
                'iso_639_3' => 'tam',
                'name_en' => 'Tamil',
                'name_native' => 'தமிழ்',
                'family' => 'Dravidian',
                'script' => 'Tamil',
                'direction' => 'ltr',
                'countries' => ['IN', 'LK', 'SG', 'MY'],
                'speakers_native' => 75000000,
                'speakers_total' => 77000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Telugu
            [
                'iso_639_1' => 'te',
                'iso_639_2' => 'tel',
                'iso_639_3' => 'tel',
                'name_en' => 'Telugu',
                'name_native' => 'తెలుగు',
                'family' => 'Dravidian',
                'script' => 'Telugu',
                'direction' => 'ltr',
                'countries' => ['IN'],
                'speakers_native' => 82000000,
                'speakers_total' => 85000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Kannada
            [
                'iso_639_1' => 'kn',
                'iso_639_2' => 'kan',
                'iso_639_3' => 'kan',
                'name_en' => 'Kannada',
                'name_native' => 'ಕನ್ನಡ',
                'family' => 'Dravidian',
                'script' => 'Kannada',
                'direction' => 'ltr',
                'countries' => ['IN'],
                'speakers_native' => 43000000,
                'speakers_total' => 47000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Malayalam
            [
                'iso_639_1' => 'ml',
                'iso_639_2' => 'mal',
                'iso_639_3' => 'mal',
                'name_en' => 'Malayalam',
                'name_native' => 'മലയാളം',
                'family' => 'Dravidian',
                'script' => 'Malayalam',
                'direction' => 'ltr',
                'countries' => ['IN'],
                'speakers_native' => 38000000,
                'speakers_total' => 41000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Gujarati
            [
                'iso_639_1' => 'gu',
                'iso_639_2' => 'guj',
                'iso_639_3' => 'guj',
                'name_en' => 'Gujarati',
                'name_native' => 'ગુજરાતી',
                'family' => 'Indo-European',
                'script' => 'Gujarati',
                'direction' => 'ltr',
                'countries' => ['IN'],
                'speakers_native' => 56000000,
                'speakers_total' => 61000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Marathi
            [
                'iso_639_1' => 'mr',
                'iso_639_2' => 'mar',
                'iso_639_3' => 'mar',
                'name_en' => 'Marathi',
                'name_native' => 'मराठी',
                'family' => 'Indo-European',
                'script' => 'Devanagari',
                'direction' => 'ltr',
                'countries' => ['IN'],
                'speakers_native' => 83000000,
                'speakers_total' => 95000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Punjabi
            [
                'iso_639_1' => 'pa',
                'iso_639_2' => 'pan',
                'iso_639_3' => 'pan',
                'name_en' => 'Punjabi',
                'name_native' => 'ਪੰਜਾਬੀ',
                'family' => 'Indo-European',
                'script' => 'Gurmukhi',
                'direction' => 'ltr',
                'countries' => ['IN', 'PK'],
                'speakers_native' => 125000000,
                'speakers_total' => 150000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Oriya
            [
                'iso_639_1' => 'or',
                'iso_639_2' => 'ori',
                'iso_639_3' => 'ori',
                'name_en' => 'Oriya',
                'name_native' => 'ଓଡ଼ିଆ',
                'family' => 'Indo-European',
                'script' => 'Oriya',
                'direction' => 'ltr',
                'countries' => ['IN'],
                'speakers_native' => 38000000,
                'speakers_total' => 39000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Assamese
            [
                'iso_639_1' => 'as',
                'iso_639_2' => 'asm',
                'iso_639_3' => 'asm',
                'name_en' => 'Assamese',
                'name_native' => 'অসমীয়া',
                'family' => 'Indo-European',
                'script' => 'Bengali',
                'direction' => 'ltr',
                'countries' => ['IN'],
                'speakers_native' => 15000000,
                'speakers_total' => 23000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Khmer
            [
                'iso_639_1' => 'km',
                'iso_639_2' => 'khm',
                'iso_639_3' => 'khm',
                'name_en' => 'Khmer',
                'name_native' => 'ភាសាខ្មែរ',
                'family' => 'Austroasiatic',
                'script' => 'Khmer',
                'direction' => 'ltr',
                'countries' => ['KH'],
                'speakers_native' => 16000000,
                'speakers_total' => 17000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Lao
            [
                'iso_639_1' => 'lo',
                'iso_639_2' => 'lao',
                'iso_639_3' => 'lao',
                'name_en' => 'Lao',
                'name_native' => 'ລາວ',
                'family' => 'Kra-Dai',
                'script' => 'Lao',
                'direction' => 'ltr',
                'countries' => ['LA'],
                'speakers_native' => 7000000,
                'speakers_total' => 25000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Burmese
            [
                'iso_639_1' => 'my',
                'iso_639_2' => 'mya',
                'iso_639_3' => 'mya',
                'name_en' => 'Burmese',
                'name_native' => 'မြန်မာဘာသာ',
                'family' => 'Sino-Tibetan',
                'script' => 'Myanmar',
                'direction' => 'ltr',
                'countries' => ['MM'],
                'speakers_native' => 33000000,
                'speakers_total' => 43000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Maori
            [
                'iso_639_1' => 'mi',
                'iso_639_2' => 'mri',
                'iso_639_3' => 'mri',
                'name_en' => 'Maori',
                'name_native' => 'Te Reo Māori',
                'family' => 'Austronesian',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['NZ'],
                'speakers_native' => 185000,
                'speakers_total' => 250000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Samoan
            [
                'iso_639_1' => 'sm',
                'iso_639_2' => 'smo',
                'iso_639_3' => 'smo',
                'name_en' => 'Samoan',
                'name_native' => 'Gagana Samoa',
                'family' => 'Austronesian',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['WS', 'AS'],
                'speakers_native' => 370000,
                'speakers_total' => 510000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Tongan
            [
                'iso_639_1' => 'to',
                'iso_639_2' => 'ton',
                'iso_639_3' => 'ton',
                'name_en' => 'Tongan',
                'name_native' => 'lea faka-Tonga',
                'family' => 'Austronesian',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['TO'],
                'speakers_native' => 96000,
                'speakers_total' => 137000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Fijian
            [
                'iso_639_1' => 'fj',
                'iso_639_2' => 'fij',
                'iso_639_3' => 'fij',
                'name_en' => 'Fijian',
                'name_native' => 'vosa Vakaviti',
                'family' => 'Austronesian',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['FJ'],
                'speakers_native' => 350000,
                'speakers_total' => 450000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Tajik
            [
                'iso_639_1' => 'tg',
                'iso_639_2' => 'tgk',
                'iso_639_3' => 'tgk',
                'name_en' => 'Tajik',
                'name_native' => 'Тоҷикӣ',
                'family' => 'Indo-European',
                'script' => 'Cyrillic',
                'direction' => 'ltr',
                'countries' => ['TJ'],
                'speakers_native' => 8000000,
                'speakers_total' => 9000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Turkmen
            [
                'iso_639_1' => 'tk',
                'iso_639_2' => 'tuk',
                'iso_639_3' => 'tuk',
                'name_en' => 'Turkmen',
                'name_native' => 'Türkmen',
                'family' => 'Turkic',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['TM'],
                'speakers_native' => 6700000,
                'speakers_total' => 8000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Kyrgyz
            [
                'iso_639_1' => 'ky',
                'iso_639_2' => 'kir',
                'iso_639_3' => 'kir',
                'name_en' => 'Kyrgyz',
                'name_native' => 'Кыргызча',
                'family' => 'Turkic',
                'script' => 'Cyrillic',
                'direction' => 'ltr',
                'countries' => ['KG'],
                'speakers_native' => 4500000,
                'speakers_total' => 5000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Dzongkha
            [
                'iso_639_1' => 'dz',
                'iso_639_2' => 'dzo',
                'iso_639_3' => 'dzo',
                'name_en' => 'Dzongkha',
                'name_native' => 'རྫོང་ཁ',
                'family' => 'Sino-Tibetan',
                'script' => 'Tibetan',
                'direction' => 'ltr',
                'countries' => ['BT'],
                'speakers_native' => 640000,
                'speakers_total' => 680000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Nepali
            [
                'iso_639_1' => 'ne',
                'iso_639_2' => 'nep',
                'iso_639_3' => 'nep',
                'name_en' => 'Nepali',
                'name_native' => 'नेपाली',
                'family' => 'Indo-European',
                'script' => 'Devanagari',
                'direction' => 'ltr',
                'countries' => ['NP', 'IN', 'BT'],
                'speakers_native' => 17000000,
                'speakers_total' => 25000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Tibetan
            [
                'iso_639_1' => 'bo',
                'iso_639_2' => 'bod',
                'iso_639_3' => 'bod',
                'name_en' => 'Tibetan',
                'name_native' => 'བོད་སྐད',
                'family' => 'Sino-Tibetan',
                'script' => 'Tibetan',
                'direction' => 'ltr',
                'countries' => ['CN', 'IN', 'NP', 'BT'],
                'speakers_native' => 1200000,
                'speakers_total' => 6000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Uyghur
            [
                'iso_639_1' => 'ug',
                'iso_639_2' => 'uig',
                'iso_639_3' => 'uig',
                'name_en' => 'Uyghur',
                'name_native' => 'ئۇيغۇرچە',
                'family' => 'Turkic',
                'script' => 'Arabic',
                'direction' => 'rtl',
                'countries' => ['CN', 'KZ', 'KG'],
                'speakers_native' => 10000000,
                'speakers_total' => 11000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Mongolian (Traditional)
            [
                'iso_639_1' => 'mn',
                'iso_639_2' => 'mon',
                'iso_639_3' => 'mon',
                'name_en' => 'Mongolian',
                'name_native' => 'Монгол',
                'family' => 'Mongolic',
                'script' => 'Cyrillic',
                'direction' => 'ltr',
                'countries' => ['MN', 'CN'],
                'speakers_native' => 5200000,
                'speakers_total' => 6000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Javanese
            [
                'iso_639_1' => 'jv',
                'iso_639_2' => 'jav',
                'iso_639_3' => 'jav',
                'name_en' => 'Javanese',
                'name_native' => 'ꦧꦱꦗꦮ',
                'family' => 'Austronesian',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['ID'],
                'speakers_native' => 84000000,
                'speakers_total' => 85000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Sundanese
            [
                'iso_639_1' => 'su',
                'iso_639_2' => 'sun',
                'iso_639_3' => 'sun',
                'name_en' => 'Sundanese',
                'name_native' => 'Basa Sunda',
                'family' => 'Austronesian',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['ID'],
                'speakers_native' => 42000000,
                'speakers_total' => 42000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Quechua
            [
                'iso_639_1' => 'qu',
                'iso_639_2' => 'que',
                'iso_639_3' => 'que',
                'name_en' => 'Quechua',
                'name_native' => 'Runa Simi',
                'family' => 'Quechuan',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['PE', 'BO', 'EC'],
                'speakers_native' => 8900000,
                'speakers_total' => 10000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Guarani
            [
                'iso_639_1' => 'gn',
                'iso_639_2' => 'grn',
                'iso_639_3' => 'grn',
                'name_en' => 'Guarani',
                'name_native' => 'Avañe\'ẽ',
                'family' => 'Tupian',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['PY', 'BO', 'AR', 'BR'],
                'speakers_native' => 6500000,
                'speakers_total' => 8000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Aymara
            [
                'iso_639_1' => 'ay',
                'iso_639_2' => 'aym',
                'iso_639_3' => 'aym',
                'name_en' => 'Aymara',
                'name_native' => 'Aymar aru',
                'family' => 'Aymaran',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['BO', 'PE', 'CL'],
                'speakers_native' => 1700000,
                'speakers_total' => 2200000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Haitian Creole
            [
                'iso_639_1' => 'ht',
                'iso_639_2' => 'hat',
                'iso_639_3' => 'hat',
                'name_en' => 'Haitian Creole',
                'name_native' => 'Kreyòl Ayisyen',
                'family' => 'Creole',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['HT'],
                'speakers_native' => 12000000,
                'speakers_total' => 12000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Greenlandic
            [
                'iso_639_1' => 'kl',
                'iso_639_2' => 'kal',
                'iso_639_3' => 'kal',
                'name_en' => 'Greenlandic',
                'name_native' => 'Kalaallisut',
                'family' => 'Eskimo-Aleut',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['GL'],
                'speakers_native' => 57000,
                'speakers_total' => 57000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Faroese
            [
                'iso_639_1' => 'fo',
                'iso_639_2' => 'fao',
                'iso_639_3' => 'fao',
                'name_en' => 'Faroese',
                'name_native' => 'Føroyskt',
                'family' => 'Indo-European',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['FO'],
                'speakers_native' => 69000,
                'speakers_total' => 72000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Swati
            [
                'iso_639_1' => 'ss',
                'iso_639_2' => 'ssw',
                'iso_639_3' => 'ssw',
                'name_en' => 'Swati',
                'name_native' => 'siSwati',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['SZ', 'ZA'],
                'speakers_native' => 2300000,
                'speakers_total' => 2400000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Ndebele
            [
                'iso_639_1' => 'nd',
                'iso_639_2' => 'nde',
                'iso_639_3' => 'nde',
                'name_en' => 'Ndebele',
                'name_native' => 'isiNdebele',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['ZW', 'ZA'],
                'speakers_native' => 1100000,
                'speakers_total' => 1600000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Tswana
            [
                'iso_639_1' => 'tn',
                'iso_639_2' => 'tsn',
                'iso_639_3' => 'tsn',
                'name_en' => 'Tswana',
                'name_native' => 'Setswana',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['BW', 'ZA'],
                'speakers_native' => 8200000,
                'speakers_total' => 8200000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Sotho
            [
                'iso_639_1' => 'st',
                'iso_639_2' => 'sot',
                'iso_639_3' => 'sot',
                'name_en' => 'Sotho',
                'name_native' => 'Sesotho',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['LS', 'ZA'],
                'speakers_native' => 5600000,
                'speakers_total' => 7900000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Kirundi
            [
                'iso_639_1' => 'rn',
                'iso_639_2' => 'run',
                'iso_639_3' => 'run',
                'name_en' => 'Kirundi',
                'name_native' => 'Ikirundi',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['BI'],
                'speakers_native' => 9000000,
                'speakers_total' => 11000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Bambara
            [
                'iso_639_1' => 'bm',
                'iso_639_2' => 'bam',
                'iso_639_3' => 'bam',
                'name_en' => 'Bambara',
                'name_native' => 'Bamanankan',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['ML'],
                'speakers_native' => 4000000,
                'speakers_total' => 14000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Wolof
            [
                'iso_639_1' => 'wo',
                'iso_639_2' => 'wol',
                'iso_639_3' => 'wol',
                'name_en' => 'Wolof',
                'name_native' => 'Wolof',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['SN', 'GM', 'MR'],
                'speakers_native' => 5200000,
                'speakers_total' => 12000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Fulah
            [
                'iso_639_1' => 'ff',
                'iso_639_2' => 'ful',
                'iso_639_3' => 'ful',
                'name_en' => 'Fulah',
                'name_native' => 'Fulfulde',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['SN', 'GN', 'ML', 'BF', 'NE', 'NG', 'CM'],
                'speakers_native' => 25000000,
                'speakers_total' => 32000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Luganda
            [
                'iso_639_1' => 'lg',
                'iso_639_2' => 'lug',
                'iso_639_3' => 'lug',
                'name_en' => 'Luganda',
                'name_native' => 'Luganda',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['UG'],
                'speakers_native' => 5600000,
                'speakers_total' => 8000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Akan
            [
                'iso_639_1' => 'ak',
                'iso_639_2' => 'aka',
                'iso_639_3' => 'aka',
                'name_en' => 'Akan',
                'name_native' => 'Akan',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['GH'],
                'speakers_native' => 11000000,
                'speakers_total' => 11000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Ewe
            [
                'iso_639_1' => 'ee',
                'iso_639_2' => 'ewe',
                'iso_639_3' => 'ewe',
                'name_en' => 'Ewe',
                'name_native' => 'Eʋegbe',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['GH', 'TG'],
                'speakers_native' => 5000000,
                'speakers_total' => 7000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Malagasy
            [
                'iso_639_1' => 'mg',
                'iso_639_2' => 'mlg',
                'iso_639_3' => 'mlg',
                'name_en' => 'Malagasy',
                'name_native' => 'Malagasy',
                'family' => 'Austronesian',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['MG'],
                'speakers_native' => 18000000,
                'speakers_total' => 20000000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Venda
            [
                'iso_639_1' => 've',
                'iso_639_2' => 'ven',
                'iso_639_3' => 'ven',
                'name_en' => 'Venda',
                'name_native' => 'Tshivenḓa',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['ZA', 'ZW'],
                'speakers_native' => 1300000,
                'speakers_total' => 1500000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Tsonga
            [
                'iso_639_1' => 'ts',
                'iso_639_2' => 'tso',
                'iso_639_3' => 'tso',
                'name_en' => 'Tsonga',
                'name_native' => 'Xitsonga',
                'family' => 'Niger-Congo',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['ZA', 'MZ'],
                'speakers_native' => 3200000,
                'speakers_total' => 3600000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Divehi
            [
                'iso_639_1' => 'dv',
                'iso_639_2' => 'div',
                'iso_639_3' => 'div',
                'name_en' => 'Divehi',
                'name_native' => 'ދިވެހި',
                'family' => 'Indo-European',
                'script' => 'Thaana',
                'direction' => 'rtl',
                'countries' => ['MV'],
                'speakers_native' => 340000,
                'speakers_total' => 350000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Bislama
            [
                'iso_639_1' => 'bi',
                'iso_639_2' => 'bis',
                'iso_639_3' => 'bis',
                'name_en' => 'Bislama',
                'name_native' => 'Bislama',
                'family' => 'Creole',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['VU'],
                'speakers_native' => 10000,
                'speakers_total' => 200000,
                'is_active' => false,
                'is_translated' => false,
            ],
            // Sango
            [
                'iso_639_1' => 'sg',
                'iso_639_2' => 'sag',
                'iso_639_3' => 'sag',
                'name_en' => 'Sango',
                'name_native' => 'Sängö',
                'family' => 'Creole',
                'script' => 'Latin',
                'direction' => 'ltr',
                'countries' => ['CF'],
                'speakers_native' => 500000,
                'speakers_total' => 5000000,
                'is_active' => false,
                'is_translated' => false,
            ],
        ];
        
        foreach ($languages as $language) {
            Language::create($language);
        }
        
        $this->command->info('Languages seeded successfully! Total: ' . count($languages));
    }
} 