<?php

namespace Database\Seeders\System;

use App\Models\System\Timezone;
use Illuminate\Database\Seeder;

class TimezonesSeeder extends Seeder
{
    public function run(): void
    {
        $timezones = [
            // UTC/GMT
            [
                'name' => 'UTC',
                'abbr' => 'UTC',
                'offset' => 0,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => null,
                'display_name' => 'Coordinated Universal Time',
                'is_active' => true,
            ],
            
            // Africa - Major timezones
            [
                'name' => 'Africa/Cairo',
                'abbr' => 'EET',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => 'EEST',
                'dst_offset' => 180,
                'country_code' => 'EG',
                'display_name' => 'Eastern European Time - Cairo',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Lagos',
                'abbr' => 'WAT',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'NG',
                'display_name' => 'West Africa Time - Lagos',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Johannesburg',
                'abbr' => 'SAST',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => 'SAST',
                'dst_offset' => 120,
                'country_code' => 'ZA',
                'display_name' => 'South Africa Standard Time',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Nairobi',
                'abbr' => 'EAT',
                'offset' => 180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'KE',
                'display_name' => 'East Africa Time',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Casablanca',
                'abbr' => 'WET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'MA',
                'display_name' => 'Western European Time - Casablanca',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Algiers',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'DZ',
                'display_name' => 'Central European Time - Algiers',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Tunis',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'TN',
                'display_name' => 'Central European Time - Tunis',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Harare',
                'abbr' => 'CAT',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'ZW',
                'display_name' => 'Central Africa Time - Harare',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Accra',
                'abbr' => 'GMT',
                'offset' => 0,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'GH',
                'display_name' => 'Greenwich Mean Time - Accra',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Addis_Ababa',
                'abbr' => 'EAT',
                'offset' => 180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'ET',
                'display_name' => 'East Africa Time - Addis Ababa',
                'is_active' => true,
            ],
            
            // Americas - North America
            [
                'name' => 'America/New_York',
                'abbr' => 'EST',
                'offset' => -300,
                'is_dst' => false,
                'dst_abbr' => 'EDT',
                'dst_offset' => -240,
                'country_code' => 'US',
                'display_name' => 'Eastern Time (US & Canada)',
                'is_active' => true,
            ],
            [
                'name' => 'America/Chicago',
                'abbr' => 'CST',
                'offset' => -360,
                'is_dst' => false,
                'dst_abbr' => 'CDT',
                'dst_offset' => -300,
                'country_code' => 'US',
                'display_name' => 'Central Time (US & Canada)',
                'is_active' => true,
            ],
            [
                'name' => 'America/Denver',
                'abbr' => 'MST',
                'offset' => -420,
                'is_dst' => false,
                'dst_abbr' => 'MDT',
                'dst_offset' => -360,
                'country_code' => 'US',
                'display_name' => 'Mountain Time (US & Canada)',
                'is_active' => true,
            ],
            [
                'name' => 'America/Los_Angeles',
                'abbr' => 'PST',
                'offset' => -480,
                'is_dst' => false,
                'dst_abbr' => 'PDT',
                'dst_offset' => -420,
                'country_code' => 'US',
                'display_name' => 'Pacific Time (US & Canada)',
                'is_active' => true,
            ],
            [
                'name' => 'America/Phoenix',
                'abbr' => 'MST',
                'offset' => -420,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'US',
                'display_name' => 'Mountain Time (Arizona)',
                'is_active' => true,
            ],
            [
                'name' => 'America/Anchorage',
                'abbr' => 'AKST',
                'offset' => -540,
                'is_dst' => false,
                'dst_abbr' => 'AKDT',
                'dst_offset' => -480,
                'country_code' => 'US',
                'display_name' => 'Alaska Time',
                'is_active' => true,
            ],
            [
                'name' => 'Pacific/Honolulu',
                'abbr' => 'HST',
                'offset' => -600,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'US',
                'display_name' => 'Hawaii-Aleutian Time',
                'is_active' => true,
            ],
            [
                'name' => 'America/Toronto',
                'abbr' => 'EST',
                'offset' => -300,
                'is_dst' => false,
                'dst_abbr' => 'EDT',
                'dst_offset' => -240,
                'country_code' => 'CA',
                'display_name' => 'Eastern Time (Canada)',
                'is_active' => true,
            ],
            [
                'name' => 'America/Vancouver',
                'abbr' => 'PST',
                'offset' => -480,
                'is_dst' => false,
                'dst_abbr' => 'PDT',
                'dst_offset' => -420,
                'country_code' => 'CA',
                'display_name' => 'Pacific Time (Canada)',
                'is_active' => true,
            ],
            [
                'name' => 'America/Edmonton',
                'abbr' => 'MST',
                'offset' => -420,
                'is_dst' => false,
                'dst_abbr' => 'MDT',
                'dst_offset' => -360,
                'country_code' => 'CA',
                'display_name' => 'Mountain Time (Canada)',
                'is_active' => true,
            ],
            [
                'name' => 'America/Winnipeg',
                'abbr' => 'CST',
                'offset' => -360,
                'is_dst' => false,
                'dst_abbr' => 'CDT',
                'dst_offset' => -300,
                'country_code' => 'CA',
                'display_name' => 'Central Time (Canada)',
                'is_active' => true,
            ],
            [
                'name' => 'America/Halifax',
                'abbr' => 'AST',
                'offset' => -240,
                'is_dst' => false,
                'dst_abbr' => 'ADT',
                'dst_offset' => -180,
                'country_code' => 'CA',
                'display_name' => 'Atlantic Time (Canada)',
                'is_active' => true,
            ],
            [
                'name' => 'America/St_Johns',
                'abbr' => 'NST',
                'offset' => -210,
                'is_dst' => false,
                'dst_abbr' => 'NDT',
                'dst_offset' => -150,
                'country_code' => 'CA',
                'display_name' => 'Newfoundland Time',
                'is_active' => true,
            ],
            [
                'name' => 'America/Mexico_City',
                'abbr' => 'CST',
                'offset' => -360,
                'is_dst' => false,
                'dst_abbr' => 'CDT',
                'dst_offset' => -300,
                'country_code' => 'MX',
                'display_name' => 'Central Time (Mexico)',
                'is_active' => true,
            ],
            [
                'name' => 'America/Tijuana',
                'abbr' => 'PST',
                'offset' => -480,
                'is_dst' => false,
                'dst_abbr' => 'PDT',
                'dst_offset' => -420,
                'country_code' => 'MX',
                'display_name' => 'Pacific Time (Mexico)',
                'is_active' => true,
            ],
            
            // Americas - Central America & Caribbean
            [
                'name' => 'America/Guatemala',
                'abbr' => 'CST',
                'offset' => -360,
                'is_dst' => false,
                'dst_abbr' => 'CDT',
                'dst_offset' => -300,
                'country_code' => 'GT',
                'display_name' => 'Central America Time',
                'is_active' => true,
            ],
            [
                'name' => 'America/Havana',
                'abbr' => 'CST',
                'offset' => -300,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'CU',
                'display_name' => 'Cuba Time',
                'is_active' => true,
            ],
            [
                'name' => 'America/Jamaica',
                'abbr' => 'EST',
                'offset' => -300,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'JM',
                'display_name' => 'Eastern Standard Time (Jamaica)',
                'is_active' => true,
            ],
            [
                'name' => 'America/Port-au-Prince',
                'abbr' => 'EST',
                'offset' => -300,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'HT',
                'display_name' => 'Eastern Time (Haiti)',
                'is_active' => true,
            ],
            [
                'name' => 'America/Santo_Domingo',
                'abbr' => 'AST',
                'offset' => -240,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'DO',
                'display_name' => 'Atlantic Standard Time (Dominican Republic)',
                'is_active' => true,
            ],
            
            // Americas - South America
            [
                'name' => 'America/Sao_Paulo',
                'abbr' => 'BRT',
                'offset' => -180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'BR',
                'display_name' => 'Brasilia Time',
                'is_active' => true,
            ],
            [
                'name' => 'America/Argentina/Buenos_Aires',
                'abbr' => 'ART',
                'offset' => -180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'AR',
                'display_name' => 'Argentina Time',
                'is_active' => true,
            ],
            [
                'name' => 'America/Santiago',
                'abbr' => 'CLT',
                'offset' => -180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'CL',
                'display_name' => 'Chile Time',
                'is_active' => true,
            ],
            [
                'name' => 'America/Lima',
                'abbr' => 'PET',
                'offset' => -300,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'PE',
                'display_name' => 'Peru Time',
                'is_active' => true,
            ],
            [
                'name' => 'America/Bogota',
                'abbr' => 'COT',
                'offset' => -300,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'CO',
                'display_name' => 'Colombia Time',
                'is_active' => true,
            ],
            [
                'name' => 'America/Caracas',
                'abbr' => 'VET',
                'offset' => -240,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'VE',
                'display_name' => 'Venezuela Time',
                'is_active' => true,
            ],
            [
                'name' => 'America/La_Paz',
                'abbr' => 'BOT',
                'offset' => -240,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'BO',
                'display_name' => 'Bolivia Time',
                'is_active' => true,
            ],
            [
                'name' => 'America/Guayaquil',
                'abbr' => 'ECT',
                'offset' => -300,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'EC',
                'display_name' => 'Ecuador Time',
                'is_active' => true,
            ],
            [
                'name' => 'America/Montevideo',
                'abbr' => 'UYT',
                'offset' => -180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'UY',
                'display_name' => 'Uruguay Time',
                'is_active' => true,
            ],
            [
                'name' => 'America/Asuncion',
                'abbr' => 'PYT',
                'offset' => -180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'PY',
                'display_name' => 'Paraguay Time',
                'is_active' => true,
            ],
            [
                'name' => 'America/Guyana',
                'abbr' => 'GYT',
                'offset' => -240,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'GY',
                'display_name' => 'Guyana Time',
                'is_active' => true,
            ],
            [
                'name' => 'America/Paramaribo',
                'abbr' => 'SRT',
                'offset' => -180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'SR',
                'display_name' => 'Suriname Time',
                'is_active' => true,
            ],
            
            // Europe
            [
                'name' => 'Europe/London',
                'abbr' => 'GMT',
                'offset' => 0,
                'is_dst' => false,
                'dst_abbr' => 'BST',
                'dst_offset' => 60,
                'country_code' => 'GB',
                'display_name' => 'Greenwich Mean Time - London',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Dublin',
                'abbr' => 'GMT',
                'offset' => 0,
                'is_dst' => false,
                'dst_abbr' => 'IST',
                'dst_offset' => 60,
                'country_code' => 'IE',
                'display_name' => 'Greenwich Mean Time - Dublin',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Lisbon',
                'abbr' => 'WET',
                'offset' => 0,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'PT',
                'display_name' => 'Western European Time - Lisbon',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Paris',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => 'CEST',
                'dst_offset' => 120,
                'country_code' => 'FR',
                'display_name' => 'Central European Time - Paris',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Berlin',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => 'CEST',
                'dst_offset' => 120,
                'country_code' => 'DE',
                'display_name' => 'Central European Time - Berlin',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Madrid',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => 'CEST',
                'dst_offset' => 120,
                'country_code' => 'ES',
                'display_name' => 'Central European Time - Madrid',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Rome',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => 'CEST',
                'dst_offset' => 120,
                'country_code' => 'IT',
                'display_name' => 'Central European Time - Rome',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Amsterdam',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => 'CEST',
                'dst_offset' => 120,
                'country_code' => 'NL',
                'display_name' => 'Central European Time - Amsterdam',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Brussels',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => 'CEST',
                'dst_offset' => 120,
                'country_code' => 'BE',
                'display_name' => 'Central European Time - Brussels',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Vienna',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => 'CEST',
                'dst_offset' => 120,
                'country_code' => 'AT',
                'display_name' => 'Central European Time - Vienna',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Warsaw',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => 'CEST',
                'dst_offset' => 120,
                'country_code' => 'PL',
                'display_name' => 'Central European Time - Warsaw',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Prague',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => 'CEST',
                'dst_offset' => 120,
                'country_code' => 'CZ',
                'display_name' => 'Central European Time - Prague',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Budapest',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => 'CEST',
                'dst_offset' => 120,
                'country_code' => 'HU',
                'display_name' => 'Central European Time - Budapest',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Zurich',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => 'CEST',
                'dst_offset' => 120,
                'country_code' => 'CH',
                'display_name' => 'Central European Time - Zurich',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Stockholm',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => 'CEST',
                'dst_offset' => 120,
                'country_code' => 'SE',
                'display_name' => 'Central European Time - Stockholm',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Oslo',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => 'CEST',
                'dst_offset' => 120,
                'country_code' => 'NO',
                'display_name' => 'Central European Time - Oslo',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Copenhagen',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => 'CEST',
                'dst_offset' => 120,
                'country_code' => 'DK',
                'display_name' => 'Central European Time - Copenhagen',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Athens',
                'abbr' => 'EET',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => 'EEST',
                'dst_offset' => 180,
                'country_code' => 'GR',
                'display_name' => 'Eastern European Time - Athens',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Helsinki',
                'abbr' => 'EET',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => 'EEST',
                'dst_offset' => 180,
                'country_code' => 'FI',
                'display_name' => 'Eastern European Time - Helsinki',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Bucharest',
                'abbr' => 'EET',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => 'EEST',
                'dst_offset' => 180,
                'country_code' => 'RO',
                'display_name' => 'Eastern European Time - Bucharest',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Sofia',
                'abbr' => 'EET',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => 'EEST',
                'dst_offset' => 180,
                'country_code' => 'BG',
                'display_name' => 'Eastern European Time - Sofia',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Istanbul',
                'abbr' => 'TRT',
                'offset' => 180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'TR',
                'display_name' => 'Turkey Time',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Moscow',
                'abbr' => 'MSK',
                'offset' => 180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'RU',
                'display_name' => 'Moscow Time',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Kiev',
                'abbr' => 'EET',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => 'EEST',
                'dst_offset' => 180,
                'country_code' => 'UA',
                'display_name' => 'Eastern European Time - Kiev',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Minsk',
                'abbr' => 'MSK',
                'offset' => 180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'BY',
                'display_name' => 'Moscow Time - Minsk',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Belgrade',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'RS',
                'display_name' => 'Central European Time - Belgrade',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Zagreb',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'HR',
                'display_name' => 'Central European Time - Zagreb',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Ljubljana',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'SI',
                'display_name' => 'Central European Time - Ljubljana',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Bratislava',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'SK',
                'display_name' => 'Central European Time - Bratislava',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Tallinn',
                'abbr' => 'EET',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => 'EEST',
                'dst_offset' => 180,
                'country_code' => 'EE',
                'display_name' => 'Eastern European Time - Tallinn',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Riga',
                'abbr' => 'EET',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => 'EEST',
                'dst_offset' => 180,
                'country_code' => 'LV',
                'display_name' => 'Eastern European Time - Riga',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Vilnius',
                'abbr' => 'EET',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => 'EEST',
                'dst_offset' => 180,
                'country_code' => 'LT',
                'display_name' => 'Eastern European Time - Vilnius',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Reykjavik',
                'abbr' => 'GMT',
                'offset' => 0,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'IS',
                'display_name' => 'Greenwich Mean Time - Reykjavik',
                'is_active' => true,
            ],
            
            // Asia - Middle East
            [
                'name' => 'Asia/Dubai',
                'abbr' => 'GST',
                'offset' => 240,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'AE',
                'display_name' => 'Gulf Standard Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Riyadh',
                'abbr' => 'AST',
                'offset' => 180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'SA',
                'display_name' => 'Arabia Standard Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Jerusalem',
                'abbr' => 'IST',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'IL',
                'display_name' => 'Israel Standard Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Beirut',
                'abbr' => 'EET',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'LB',
                'display_name' => 'Eastern European Time - Beirut',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Damascus',
                'abbr' => 'EET',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'SY',
                'display_name' => 'Eastern European Time - Damascus',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Amman',
                'abbr' => 'EET',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'JO',
                'display_name' => 'Eastern European Time - Amman',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Baghdad',
                'abbr' => 'AST',
                'offset' => 180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'IQ',
                'display_name' => 'Arabia Standard Time - Baghdad',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Kuwait',
                'abbr' => 'AST',
                'offset' => 180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'KW',
                'display_name' => 'Arabia Standard Time - Kuwait',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Qatar',
                'abbr' => 'AST',
                'offset' => 180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'QA',
                'display_name' => 'Arabia Standard Time - Qatar',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Bahrain',
                'abbr' => 'AST',
                'offset' => 180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'BH',
                'display_name' => 'Arabia Standard Time - Bahrain',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Muscat',
                'abbr' => 'GST',
                'offset' => 240,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'OM',
                'display_name' => 'Gulf Standard Time - Muscat',
                'is_active' => true,
            ],
            
            // Asia - Central Asia
            [
                'name' => 'Asia/Tehran',
                'abbr' => 'IRST',
                'offset' => 210,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'IR',
                'display_name' => 'Iran Standard Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Baku',
                'abbr' => 'AZT',
                'offset' => 240,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'AZ',
                'display_name' => 'Azerbaijan Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Yerevan',
                'abbr' => 'AMT',
                'offset' => 240,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'AM',
                'display_name' => 'Armenia Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Tbilisi',
                'abbr' => 'GET',
                'offset' => 240,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'GE',
                'display_name' => 'Georgia Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Kabul',
                'abbr' => 'AFT',
                'offset' => 270,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'AF',
                'display_name' => 'Afghanistan Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Karachi',
                'abbr' => 'PKT',
                'offset' => 300,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'PK',
                'display_name' => 'Pakistan Standard Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Tashkent',
                'abbr' => 'UZT',
                'offset' => 300,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'UZ',
                'display_name' => 'Uzbekistan Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Almaty',
                'abbr' => 'ALMT',
                'offset' => 360,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'KZ',
                'display_name' => 'Almaty Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Bishkek',
                'abbr' => 'ALMT',
                'offset' => 360,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'KG',
                'display_name' => 'Kyrgyzstan Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Ashgabat',
                'abbr' => 'TMT',
                'offset' => 300,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'TM',
                'display_name' => 'Turkmenistan Time',
                'is_active' => true,
            ],
            
            // Asia - South Asia
            [
                'name' => 'Asia/Kolkata',
                'abbr' => 'IST',
                'offset' => 330,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'IN',
                'display_name' => 'India Standard Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Colombo',
                'abbr' => 'IST',
                'offset' => 330,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'LK',
                'display_name' => 'Sri Lanka Standard Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Dhaka',
                'abbr' => 'BST',
                'offset' => 360,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'BD',
                'display_name' => 'Bangladesh Standard Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Kathmandu',
                'abbr' => 'NPT',
                'offset' => 345,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'NP',
                'display_name' => 'Nepal Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Thimphu',
                'abbr' => 'BTT',
                'offset' => 360,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'BT',
                'display_name' => 'Bhutan Time',
                'is_active' => true,
            ],
            
            // Asia - Southeast Asia
            [
                'name' => 'Asia/Bangkok',
                'abbr' => 'ICT',
                'offset' => 420,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'TH',
                'display_name' => 'Indochina Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Jakarta',
                'abbr' => 'WIB',
                'offset' => 420,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'ID',
                'display_name' => 'Western Indonesia Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Singapore',
                'abbr' => 'SGT',
                'offset' => 480,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'SG',
                'display_name' => 'Singapore Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Kuala_Lumpur',
                'abbr' => 'MYT',
                'offset' => 480,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'MY',
                'display_name' => 'Malaysia Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Manila',
                'abbr' => 'PST',
                'offset' => 480,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'PH',
                'display_name' => 'Philippine Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Ho_Chi_Minh',
                'abbr' => 'ICT',
                'offset' => 420,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'VN',
                'display_name' => 'Indochina Time - Vietnam',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Phnom_Penh',
                'abbr' => 'ICT',
                'offset' => 420,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'KH',
                'display_name' => 'Indochina Time - Cambodia',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Vientiane',
                'abbr' => 'ICT',
                'offset' => 420,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'LA',
                'display_name' => 'Indochina Time - Laos',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Yangon',
                'abbr' => 'MMT',
                'offset' => 390,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'MM',
                'display_name' => 'Myanmar Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Brunei',
                'abbr' => 'BNT',
                'offset' => 480,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'BN',
                'display_name' => 'Brunei Time',
                'is_active' => true,
            ],
            
            // Asia - East Asia
            [
                'name' => 'Asia/Tokyo',
                'abbr' => 'JST',
                'offset' => 540,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'JP',
                'display_name' => 'Japan Standard Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Seoul',
                'abbr' => 'KST',
                'offset' => 540,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'KR',
                'display_name' => 'Korea Standard Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Shanghai',
                'abbr' => 'CST',
                'offset' => 480,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'CN',
                'display_name' => 'China Standard Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Hong_Kong',
                'abbr' => 'HKT',
                'offset' => 480,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'HK',
                'display_name' => 'Hong Kong Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Taipei',
                'abbr' => 'CST',
                'offset' => 480,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'TW',
                'display_name' => 'Taiwan Standard Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Macau',
                'abbr' => 'CST',
                'offset' => 480,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'MO',
                'display_name' => 'Macau Standard Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Pyongyang',
                'abbr' => 'KST',
                'offset' => 540,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'KP',
                'display_name' => 'Pyongyang Time',
                'is_active' => true,
            ],
            [
                'name' => 'Asia/Ulaanbaatar',
                'abbr' => 'ULAT',
                'offset' => 480,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'MN',
                'display_name' => 'Mongolia Time',
                'is_active' => true,
            ],
            
            // Oceania
            [
                'name' => 'Australia/Sydney',
                'abbr' => 'AEDT',
                'offset' => 600,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'AU',
                'display_name' => 'Australian Eastern Time - Sydney',
                'is_active' => true,
            ],
            [
                'name' => 'Australia/Melbourne',
                'abbr' => 'AEDT',
                'offset' => 600,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'AU',
                'display_name' => 'Australian Eastern Time - Melbourne',
                'is_active' => true,
            ],
            [
                'name' => 'Australia/Brisbane',
                'abbr' => 'AEST',
                'offset' => 600,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'AU',
                'display_name' => 'Australian Eastern Time - Brisbane',
                'is_active' => true,
            ],
            [
                'name' => 'Australia/Perth',
                'abbr' => 'AWST',
                'offset' => 480,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'AU',
                'display_name' => 'Australian Western Time',
                'is_active' => true,
            ],
            [
                'name' => 'Australia/Adelaide',
                'abbr' => 'ACST',
                'offset' => 570,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'AU',
                'display_name' => 'Australian Central Time',
                'is_active' => true,
            ],
            [
                'name' => 'Australia/Darwin',
                'abbr' => 'ACST',
                'offset' => 570,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'AU',
                'display_name' => 'Australian Central Time - Darwin',
                'is_active' => true,
            ],
            [
                'name' => 'Australia/Hobart',
                'abbr' => 'AEDT',
                'offset' => 600,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'AU',
                'display_name' => 'Australian Eastern Time - Hobart',
                'is_active' => true,
            ],
            [
                'name' => 'Pacific/Auckland',
                'abbr' => 'NZST',
                'offset' => 720,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'NZ',
                'display_name' => 'New Zealand Standard Time',
                'is_active' => true,
            ],
            [
                'name' => 'Pacific/Fiji',
                'abbr' => 'FJT',
                'offset' => 720,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'FJ',
                'display_name' => 'Fiji Time',
                'is_active' => true,
            ],
            [
                'name' => 'Pacific/Port_Moresby',
                'abbr' => 'PGT',
                'offset' => 600,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'PG',
                'display_name' => 'Papua New Guinea Time',
                'is_active' => true,
            ],
            [
                'name' => 'Pacific/Guam',
                'abbr' => 'ChST',
                'offset' => 600,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'GU',
                'display_name' => 'Chamorro Standard Time',
                'is_active' => true,
            ],
            [
                'name' => 'Pacific/Noumea',
                'abbr' => 'NCT',
                'offset' => 660,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'NC',
                'display_name' => 'New Caledonia Time',
                'is_active' => true,
            ],
            [
                'name' => 'Pacific/Tahiti',
                'abbr' => 'TAHT',
                'offset' => -600,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'PF',
                'display_name' => 'Tahiti Time',
                'is_active' => true,
            ],
            [
                'name' => 'Pacific/Samoa',
                'abbr' => 'SST',
                'offset' => -660,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'WS',
                'display_name' => 'Samoa Standard Time',
                'is_active' => true,
            ],
            [
                'name' => 'Pacific/Tongatapu',
                'abbr' => 'TOT',
                'offset' => 780,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'TO',
                'display_name' => 'Tonga Time',
                'is_active' => true,
            ],
            
            // Additional African timezones
            [
                'name' => 'Africa/Dakar',
                'abbr' => 'GMT',
                'offset' => 0,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'SN',
                'display_name' => 'Greenwich Mean Time - Dakar',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Abidjan',
                'abbr' => 'GMT',
                'offset' => 0,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'CI',
                'display_name' => 'Greenwich Mean Time - Abidjan',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Kinshasa',
                'abbr' => 'WAT',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'CD',
                'display_name' => 'West Africa Time - Kinshasa',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Kigali',
                'abbr' => 'CAT',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'RW',
                'display_name' => 'Central Africa Time - Kigali',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Kampala',
                'abbr' => 'EAT',
                'offset' => 180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'UG',
                'display_name' => 'East Africa Time - Kampala',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Dar_es_Salaam',
                'abbr' => 'EAT',
                'offset' => 180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'TZ',
                'display_name' => 'East Africa Time - Dar es Salaam',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Mogadishu',
                'abbr' => 'EAT',
                'offset' => 180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'SO',
                'display_name' => 'East Africa Time - Mogadishu',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Djibouti',
                'abbr' => 'EAT',
                'offset' => 180,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'DJ',
                'display_name' => 'East Africa Time - Djibouti',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Maputo',
                'abbr' => 'CAT',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'MZ',
                'display_name' => 'Central Africa Time - Maputo',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Lusaka',
                'abbr' => 'CAT',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'ZM',
                'display_name' => 'Central Africa Time - Lusaka',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Windhoek',
                'abbr' => 'WAT',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'NA',
                'display_name' => 'Central Africa Time - Windhoek',
                'is_active' => true,
            ],
            [
                'name' => 'Africa/Libreville',
                'abbr' => 'WAT',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'GA',
                'display_name' => 'West Africa Time - Libreville',
                'is_active' => true,
            ],
            
            // Atlantic Ocean Islands
            [
                'name' => 'Atlantic/Azores',
                'abbr' => 'AZOT',
                'offset' => -60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'PT',
                'display_name' => 'Azores Time',
                'is_active' => true,
            ],
            [
                'name' => 'Atlantic/Cape_Verde',
                'abbr' => 'CVT',
                'offset' => -60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'CV',
                'display_name' => 'Cape Verde Time',
                'is_active' => true,
            ],
            [
                'name' => 'Atlantic/Canary',
                'abbr' => 'WET',
                'offset' => 0,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'ES',
                'display_name' => 'Western European Time - Canary',
                'is_active' => true,
            ],
            [
                'name' => 'Atlantic/Bermuda',
                'abbr' => 'AST',
                'offset' => -240,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'BM',
                'display_name' => 'Atlantic Time - Bermuda',
                'is_active' => true,
            ],
            
            // Indian Ocean
            [
                'name' => 'Indian/Mauritius',
                'abbr' => 'MUT',
                'offset' => 240,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'MU',
                'display_name' => 'Mauritius Time',
                'is_active' => true,
            ],
            [
                'name' => 'Indian/Maldives',
                'abbr' => 'MVT',
                'offset' => 300,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'MV',
                'display_name' => 'Maldives Time',
                'is_active' => true,
            ],
            [
                'name' => 'Indian/Seychelles',
                'abbr' => 'SCT',
                'offset' => 240,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'SC',
                'display_name' => 'Seychelles Time',
                'is_active' => true,
            ],
            
            // Additional regions
            [
                'name' => 'Asia/Nicosia',
                'abbr' => 'EET',
                'offset' => 120,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'CY',
                'display_name' => 'Eastern European Time - Cyprus',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Malta',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'MT',
                'display_name' => 'Central European Time - Malta',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Luxembourg',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'LU',
                'display_name' => 'Central European Time - Luxembourg',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Monaco',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'MC',
                'display_name' => 'Central European Time - Monaco',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Vatican',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'VA',
                'display_name' => 'Central European Time - Vatican',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/San_Marino',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'SM',
                'display_name' => 'Central European Time - San Marino',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Andorra',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'AD',
                'display_name' => 'Central European Time - Andorra',
                'is_active' => true,
            ],
            [
                'name' => 'Europe/Gibraltar',
                'abbr' => 'CET',
                'offset' => 60,
                'is_dst' => false,
                'dst_abbr' => null,
                'dst_offset' => null,
                'country_code' => 'GI',
                'display_name' => 'Central European Time - Gibraltar',
                'is_active' => true,
            ],
        ];
        
        foreach ($timezones as $timezone) {
            Timezone::create($timezone);
        }
        
        $this->command->info('Timezones seeded successfully! Total: ' . count($timezones));
    }
} 